### ISSUE TITLE
Support the 12ID monochromator with bluesky

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/bluesky#6]
Need to set and read energy.  There may be details how to operate it.  It's not a Kohzu monochromator.

**Comment by prjemian** [comment]
Started asking in BCDA for experience with this monochromator.

**Comment by prjemian** [comment]
EPICS database: /net/s12dserv/xorApps/epics/synApps_6_1/ioc/12ida1/db/SB_DCM.db

IOC: https://git.aps.anl.gov/12ID/12ida1

**Comment by prjemian** [comment]
Review the existing SPEC controls.

**Comment by prjemian** [comment]
In the EPICS database...

Choices like this need to be considered by the users of the controls:

```
record(bo, "$(P)Z2_Mode") {  field(ZNAM, "Freeze Z2")  field(ONAM, "Move Z2")}
```

Bluesky can avoid exposing this PV.

**Comment by prjemian** [comment]
Thinking energy and wavelength should both be positioner Components so they act like motors, as part of a monochromator Device.  Will need additional Components for things like `Z2_Mode` PV.  Also, if there is any caution of _adjust this before that_, we'll need Components for each such PV and a procedure for such adjustment.

**Comment by jilavsky** [comment]
Tested 10-26 and looks like we need tolerance value. Trying 0.0002

**Comment by jilavsky** [comment]
Success, added tolerance and get mono E scans, however, the BS crashed again, see issue #7. Looks like #7 is showstopper at this time. Am I the only one or why is this the case?

**Comment by jilavsky** [comment]
Monochromator works as needed now, energy can be scanned, energy and wavelength can be recorded to metadata. This issue is fixed.
